---
sidebar: sidebar 
permalink: task-administer-storagegrid.html 
keywords: grid manager, advanced view, standard view, use grid manager, gridmanager 
summary: 詳細ビューを使用して、 NetApp ConsoleからStorageGRIDシステムを管理します。このビューを使用すると、 NetApp Console内から Grid Manager を使用できます。 
---
= NetApp ConsoleのGrid Managerを使用してStorageGRIDを管理する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
詳細ビューを使用して、コンソールからStorageGRIDシステムを管理します。このビューを使用すると、コンソールから Grid Manager を使用できます。

.必要なNetApp Consoleロール:
ストレージ管理者、またはシステムヘルススペシャリスト。link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["アクセスロールについて学ぶ"^]。



== サポートされている構成

Grid Manager は、 StorageGRID 11.8 以降のコンソールで使用できます。



== 制限事項

次のグリッド マネージャ操作はコンソールからは使用できません。これらの操作を実行する必要がある場合は、Grid Manager に直接サインインしてください。

[cols="1a,3a"]
|===
| グリッドマネージャーメニュー | コンソールから利用できない操作 


 a| 
ユーザ
 a| 
* サインアウトリンク
* APIドキュメントリンク
* パスワードの変更




 a| 
ノード
 a| 
* 「ノード」> 「SANtricity System Manager」タブからSANtricity System Manager にアクセスできません。
* アラートを表示するときに、推奨アクションのすべてのリンクを選択できない場合があります。たとえば、サポートされていないグリッド マネージャー ページに移動するリンクは機能しません。




 a| 
テナント
 a| 
テナントの作成ウィザードまたはテナント ページからテナント アカウントにサインインすることはできません。

コンソールは現在、テナント マネージャーをサポートしていません。コンソールから新しいテナント アカウントを作成することはできますが、テナント ユーザーはコンソールから自分のアカウントにサインインすることはできません。



 a| 
ILM
 a| 
保管グレードリンク



 a| 
構成
 a| 
* グリッドパスワード
* セキュリティ設定 > ブラウザの非アクティブタイムアウト
* シングルサインオン
* SNMPエージェント > BMCインターフェースのMIBファイル




 a| 
メンテナンス
 a| 
* リカバリパッケージ
* ソフトウェアアップデート




 a| 
サポート
 a| 
* グリッドトポロジー
* ログ収集
* Prometheus メトリックと Grafana ダッシュボードへのすべてのリンク
* レガシーアラームのすべてのオプション
* リンクコスト
* NMSエンティティ


|===


== グリッドマネージャーに切り替える

StorageGRIDシステムを開き、Grid Manager オプションを選択します。

.手順
. *システム* ページから、 StorageGRIDシステムを開きます。
. 右上で、[グリッド マネージャーに切り替える] を選択します。
. Grid Manager を使用してStorageGRIDシステムを管理します。
. 必要に応じて、[*戻る*] を選択して、コンソールから標準ビューに戻ります。




== グリッドマネージャーのヘルプ

グリッドマネージャの使用に関するヘルプが必要な場合は、 https://docs.netapp.com/us-en/storagegrid/admin/index.html["StorageGRIDドキュメント"^] ステップバイステップの手順についてはこちらをご覧ください。
